Use service instead of deprecated plist_options
cockroachdb/homebrew-tap pull request #134
Opened 2023-02-16 14:49 UTC by thadc23

Fixing this warning message:

```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the cockroachdb/tap tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/cockroachdb/homebrew-tap/Formula/cockroach.rb:62
```

2023-02-16 20:06 UTC, rail commented
oops, just realized that you submitted this PR :)
I created https://github.com/cockroachdb/homebrew-tap/pull/136 which contains [this condition](https://github.com/cockroachdb/homebrew-tap/pull/136/files#diff-10d1c12c97dc80980ba3b97e51d4bae24ee4e9a4690a63844ddfa2efdc172362R70-R72) for M1 Macs. Can you incorporate it please.

2023-02-16 20:08 UTC, rail commented on Formula/cockroach.rb
> +    run [bin/"cockroach", "start-single-node", "--insecure", "--http-port=26256", "--host=localhost"]
I think this should be `opt_bin`

2023-02-16 21:00 UTC, rail requested changes
Can you also update https://github.com/cockroachdb/homebrew-tap/blob/cefa6e7254d0fb1755cd06ade30b152653accf85/release/cockroach-tmpl.rb#L62

2023-02-17 15:42 UTC, thadc23 commented
Working on these.  Thanks!

2023-02-17 15:50 UTC, thadc23 commented
@rail Should be incorporated now.

2023-02-17 19:44 UTC, rail approved these changes
TYVM!

2023-02-17 19:44 UTC, merged